export * from "./IAddable"
export * from "./IAdditiveIdentity"
export * from "./IComparable"
export * from "./IDivideable"
export * from "./IEquatable"
export * from "./IMultipliable"
export * from "./IMultiplicativeIdentity"
export * from "./ISubtractable"
